// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: gluon/customauth/pairing.proto

package types

import (
	fmt "fmt"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	github_com_cosmos_gogoproto_types "github.com/cosmos/gogoproto/types"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	io "io"
	math "math"
	math_bits "math/bits"
	time "time"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf
var _ = time.Kitchen

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type Pairing struct {
	Id        uint64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Address   string    `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	PublicKey string    `protobuf:"bytes,3,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	CreatedAt time.Time `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3,stdtime" json:"created_at"`
}

func (m *Pairing) Reset()         { *m = Pairing{} }
func (m *Pairing) String() string { return proto.CompactTextString(m) }
func (*Pairing) ProtoMessage()    {}
func (*Pairing) Descriptor() ([]byte, []int) {
	return fileDescriptor_6b971e3bc1d64983, []int{0}
}
func (m *Pairing) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Pairing) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Pairing.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Pairing) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Pairing.Merge(m, src)
}
func (m *Pairing) XXX_Size() int {
	return m.Size()
}
func (m *Pairing) XXX_DiscardUnknown() {
	xxx_messageInfo_Pairing.DiscardUnknown(m)
}

var xxx_messageInfo_Pairing proto.InternalMessageInfo

func (m *Pairing) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Pairing) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *Pairing) GetPublicKey() string {
	if m != nil {
		return m.PublicKey
	}
	return ""
}

func (m *Pairing) GetCreatedAt() time.Time {
	if m != nil {
		return m.CreatedAt
	}
	return time.Time{}
}

func init() {
	proto.RegisterType((*Pairing)(nil), "gluon.customauth.Pairing")
}

func init() { proto.RegisterFile("gluon/customauth/pairing.proto", fileDescriptor_6b971e3bc1d64983) }

var fileDescriptor_6b971e3bc1d64983 = []byte{
	// 262 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x90, 0x31, 0x4b, 0xc4, 0x30,
	0x1c, 0xc5, 0x9b, 0x7a, 0x78, 0x36, 0x82, 0x48, 0x71, 0x08, 0x05, 0xd3, 0xe2, 0xd4, 0xa9, 0x85,
	0xf3, 0x13, 0x78, 0x8e, 0x2e, 0x52, 0x9c, 0x5c, 0x8e, 0xb4, 0x89, 0x31, 0xd8, 0x5e, 0x42, 0x93,
	0x80, 0xfd, 0x16, 0xb7, 0xf9, 0x95, 0x6e, 0xbc, 0xd1, 0x49, 0xa5, 0xfd, 0x22, 0x62, 0x62, 0xd1,
	0x2d, 0x2f, 0xbf, 0xf7, 0x7f, 0x3c, 0x1e, 0xc4, 0xbc, 0xb5, 0x72, 0x5b, 0x36, 0x56, 0x1b, 0xd9,
	0x11, 0x6b, 0x9e, 0x4b, 0x45, 0x44, 0x2f, 0xb6, 0xbc, 0x50, 0xbd, 0x34, 0x32, 0x3e, 0x77, 0xbc,
	0xf8, 0xe3, 0xc9, 0x05, 0x97, 0x5c, 0x3a, 0x58, 0xfe, 0xbc, 0xbc, 0x2f, 0x49, 0xb9, 0x94, 0xbc,
	0x65, 0xa5, 0x53, 0xb5, 0x7d, 0x2a, 0x8d, 0xe8, 0x98, 0x36, 0xa4, 0x53, 0xde, 0x70, 0xf5, 0x06,
	0xe0, 0xf2, 0xde, 0x47, 0xc7, 0x67, 0x30, 0x14, 0x14, 0x81, 0x0c, 0xe4, 0x8b, 0x2a, 0x14, 0x34,
	0x46, 0x70, 0x49, 0x28, 0xed, 0x99, 0xd6, 0x28, 0xcc, 0x40, 0x1e, 0x55, 0xb3, 0x8c, 0x2f, 0x21,
	0x54, 0xb6, 0x6e, 0x45, 0xb3, 0x79, 0x61, 0x03, 0x3a, 0x72, 0x30, 0xf2, 0x3f, 0x77, 0x6c, 0x88,
	0x6f, 0x21, 0x6c, 0x7a, 0x46, 0x0c, 0xa3, 0x1b, 0x62, 0xd0, 0x22, 0x03, 0xf9, 0xe9, 0x2a, 0x29,
	0x7c, 0x95, 0x62, 0xae, 0x52, 0x3c, 0xcc, 0x55, 0xd6, 0x27, 0xfb, 0x8f, 0x34, 0xd8, 0x7d, 0xa6,
	0xa0, 0x8a, 0x7e, 0xef, 0x6e, 0xcc, 0x7a, 0xb5, 0x1f, 0x31, 0x38, 0x8c, 0x18, 0x7c, 0x8d, 0x18,
	0xec, 0x26, 0x1c, 0x1c, 0x26, 0x1c, 0xbc, 0x4f, 0x38, 0x78, 0x44, 0x7e, 0x9c, 0xd7, 0xff, 0xf3,
	0x98, 0x41, 0x31, 0x5d, 0x1f, 0xbb, 0xf0, 0xeb, 0xef, 0x00, 0x00, 0x00, 0xff, 0xff, 0x2e, 0x61,
	0xb8, 0x06, 0x3f, 0x01, 0x00, 0x00,
}

func (m *Pairing) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Pairing) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Pairing) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	n1, err1 := github_com_cosmos_gogoproto_types.StdTimeMarshalTo(m.CreatedAt, dAtA[i-github_com_cosmos_gogoproto_types.SizeOfStdTime(m.CreatedAt):])
	if err1 != nil {
		return 0, err1
	}
	i -= n1
	i = encodeVarintPairing(dAtA, i, uint64(n1))
	i--
	dAtA[i] = 0x22
	if len(m.PublicKey) > 0 {
		i -= len(m.PublicKey)
		copy(dAtA[i:], m.PublicKey)
		i = encodeVarintPairing(dAtA, i, uint64(len(m.PublicKey)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Address) > 0 {
		i -= len(m.Address)
		copy(dAtA[i:], m.Address)
		i = encodeVarintPairing(dAtA, i, uint64(len(m.Address)))
		i--
		dAtA[i] = 0x12
	}
	if m.Id != 0 {
		i = encodeVarintPairing(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintPairing(dAtA []byte, offset int, v uint64) int {
	offset -= sovPairing(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Pairing) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Id != 0 {
		n += 1 + sovPairing(uint64(m.Id))
	}
	l = len(m.Address)
	if l > 0 {
		n += 1 + l + sovPairing(uint64(l))
	}
	l = len(m.PublicKey)
	if l > 0 {
		n += 1 + l + sovPairing(uint64(l))
	}
	l = github_com_cosmos_gogoproto_types.SizeOfStdTime(m.CreatedAt)
	n += 1 + l + sovPairing(uint64(l))
	return n
}

func sovPairing(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozPairing(x uint64) (n int) {
	return sovPairing(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Pairing) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowPairing
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Pairing: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Pairing: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPairing
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Address", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPairing
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPairing
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPairing
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Address = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PublicKey", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPairing
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPairing
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPairing
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PublicKey = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CreatedAt", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPairing
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthPairing
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthPairing
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_cosmos_gogoproto_types.StdTimeUnmarshal(&m.CreatedAt, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipPairing(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthPairing
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipPairing(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowPairing
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowPairing
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowPairing
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthPairing
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupPairing
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthPairing
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthPairing        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowPairing          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupPairing = fmt.Errorf("proto: unexpected end of group")
)
