// Code generated by protoc-gen-go-pulsar. DO NOT EDIT.
package contract

import (
	_ "cosmossdk.io/api/amino"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	runtime "github.com/cosmos/cosmos-proto/runtime"
	_ "github.com/cosmos/gogoproto/gogoproto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoiface "google.golang.org/protobuf/runtime/protoiface"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	io "io"
	reflect "reflect"
	sync "sync"
)

var (
	md_LazyContract                       protoreflect.MessageDescriptor
	fd_LazyContract_id                    protoreflect.FieldDescriptor
	fd_LazyContract_buyer                 protoreflect.FieldDescriptor
	fd_LazyContract_seller                protoreflect.FieldDescriptor
	fd_LazyContract_denom_base            protoreflect.FieldDescriptor
	fd_LazyContract_denom_quote           protoreflect.FieldDescriptor
	fd_LazyContract_amount_pending_buyer  protoreflect.FieldDescriptor
	fd_LazyContract_amount_pending_seller protoreflect.FieldDescriptor
	fd_LazyContract_amount_escrow_buyer   protoreflect.FieldDescriptor
	fd_LazyContract_amount_escrow_seller  protoreflect.FieldDescriptor
	fd_LazyContract_expiry                protoreflect.FieldDescriptor
)

func init() {
	file_gluon_contract_lazy_contract_proto_init()
	md_LazyContract = File_gluon_contract_lazy_contract_proto.Messages().ByName("LazyContract")
	fd_LazyContract_id = md_LazyContract.Fields().ByName("id")
	fd_LazyContract_buyer = md_LazyContract.Fields().ByName("buyer")
	fd_LazyContract_seller = md_LazyContract.Fields().ByName("seller")
	fd_LazyContract_denom_base = md_LazyContract.Fields().ByName("denom_base")
	fd_LazyContract_denom_quote = md_LazyContract.Fields().ByName("denom_quote")
	fd_LazyContract_amount_pending_buyer = md_LazyContract.Fields().ByName("amount_pending_buyer")
	fd_LazyContract_amount_pending_seller = md_LazyContract.Fields().ByName("amount_pending_seller")
	fd_LazyContract_amount_escrow_buyer = md_LazyContract.Fields().ByName("amount_escrow_buyer")
	fd_LazyContract_amount_escrow_seller = md_LazyContract.Fields().ByName("amount_escrow_seller")
	fd_LazyContract_expiry = md_LazyContract.Fields().ByName("expiry")
}

var _ protoreflect.Message = (*fastReflection_LazyContract)(nil)

type fastReflection_LazyContract LazyContract

func (x *LazyContract) ProtoReflect() protoreflect.Message {
	return (*fastReflection_LazyContract)(x)
}

func (x *LazyContract) slowProtoReflect() protoreflect.Message {
	mi := &file_gluon_contract_lazy_contract_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

var _fastReflection_LazyContract_messageType fastReflection_LazyContract_messageType
var _ protoreflect.MessageType = fastReflection_LazyContract_messageType{}

type fastReflection_LazyContract_messageType struct{}

func (x fastReflection_LazyContract_messageType) Zero() protoreflect.Message {
	return (*fastReflection_LazyContract)(nil)
}
func (x fastReflection_LazyContract_messageType) New() protoreflect.Message {
	return new(fastReflection_LazyContract)
}
func (x fastReflection_LazyContract_messageType) Descriptor() protoreflect.MessageDescriptor {
	return md_LazyContract
}

// Descriptor returns message descriptor, which contains only the protobuf
// type information for the message.
func (x *fastReflection_LazyContract) Descriptor() protoreflect.MessageDescriptor {
	return md_LazyContract
}

// Type returns the message type, which encapsulates both Go and protobuf
// type information. If the Go type information is not needed,
// it is recommended that the message descriptor be used instead.
func (x *fastReflection_LazyContract) Type() protoreflect.MessageType {
	return _fastReflection_LazyContract_messageType
}

// New returns a newly allocated and mutable empty message.
func (x *fastReflection_LazyContract) New() protoreflect.Message {
	return new(fastReflection_LazyContract)
}

// Interface unwraps the message reflection interface and
// returns the underlying ProtoMessage interface.
func (x *fastReflection_LazyContract) Interface() protoreflect.ProtoMessage {
	return (*LazyContract)(x)
}

// Range iterates over every populated field in an undefined order,
// calling f for each field descriptor and value encountered.
// Range returns immediately if f returns false.
// While iterating, mutating operations may only be performed
// on the current field descriptor.
func (x *fastReflection_LazyContract) Range(f func(protoreflect.FieldDescriptor, protoreflect.Value) bool) {
	if x.Id != uint64(0) {
		value := protoreflect.ValueOfUint64(x.Id)
		if !f(fd_LazyContract_id, value) {
			return
		}
	}
	if x.Buyer != "" {
		value := protoreflect.ValueOfString(x.Buyer)
		if !f(fd_LazyContract_buyer, value) {
			return
		}
	}
	if x.Seller != "" {
		value := protoreflect.ValueOfString(x.Seller)
		if !f(fd_LazyContract_seller, value) {
			return
		}
	}
	if x.DenomBase != "" {
		value := protoreflect.ValueOfString(x.DenomBase)
		if !f(fd_LazyContract_denom_base, value) {
			return
		}
	}
	if x.DenomQuote != "" {
		value := protoreflect.ValueOfString(x.DenomQuote)
		if !f(fd_LazyContract_denom_quote, value) {
			return
		}
	}
	if x.AmountPendingBuyer != "" {
		value := protoreflect.ValueOfString(x.AmountPendingBuyer)
		if !f(fd_LazyContract_amount_pending_buyer, value) {
			return
		}
	}
	if x.AmountPendingSeller != "" {
		value := protoreflect.ValueOfString(x.AmountPendingSeller)
		if !f(fd_LazyContract_amount_pending_seller, value) {
			return
		}
	}
	if x.AmountEscrowBuyer != "" {
		value := protoreflect.ValueOfString(x.AmountEscrowBuyer)
		if !f(fd_LazyContract_amount_escrow_buyer, value) {
			return
		}
	}
	if x.AmountEscrowSeller != "" {
		value := protoreflect.ValueOfString(x.AmountEscrowSeller)
		if !f(fd_LazyContract_amount_escrow_seller, value) {
			return
		}
	}
	if x.Expiry != nil {
		value := protoreflect.ValueOfMessage(x.Expiry.ProtoReflect())
		if !f(fd_LazyContract_expiry, value) {
			return
		}
	}
}

// Has reports whether a field is populated.
//
// Some fields have the property of nullability where it is possible to
// distinguish between the default value of a field and whether the field
// was explicitly populated with the default value. Singular message fields,
// member fields of a oneof, and proto2 scalar fields are nullable. Such
// fields are populated only if explicitly set.
//
// In other cases (aside from the nullable cases above),
// a proto3 scalar field is populated if it contains a non-zero value, and
// a repeated field is populated if it is non-empty.
func (x *fastReflection_LazyContract) Has(fd protoreflect.FieldDescriptor) bool {
	switch fd.FullName() {
	case "gluon.contract.LazyContract.id":
		return x.Id != uint64(0)
	case "gluon.contract.LazyContract.buyer":
		return x.Buyer != ""
	case "gluon.contract.LazyContract.seller":
		return x.Seller != ""
	case "gluon.contract.LazyContract.denom_base":
		return x.DenomBase != ""
	case "gluon.contract.LazyContract.denom_quote":
		return x.DenomQuote != ""
	case "gluon.contract.LazyContract.amount_pending_buyer":
		return x.AmountPendingBuyer != ""
	case "gluon.contract.LazyContract.amount_pending_seller":
		return x.AmountPendingSeller != ""
	case "gluon.contract.LazyContract.amount_escrow_buyer":
		return x.AmountEscrowBuyer != ""
	case "gluon.contract.LazyContract.amount_escrow_seller":
		return x.AmountEscrowSeller != ""
	case "gluon.contract.LazyContract.expiry":
		return x.Expiry != nil
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: gluon.contract.LazyContract"))
		}
		panic(fmt.Errorf("message gluon.contract.LazyContract does not contain field %s", fd.FullName()))
	}
}

// Clear clears the field such that a subsequent Has call reports false.
//
// Clearing an extension field clears both the extension type and value
// associated with the given field number.
//
// Clear is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_LazyContract) Clear(fd protoreflect.FieldDescriptor) {
	switch fd.FullName() {
	case "gluon.contract.LazyContract.id":
		x.Id = uint64(0)
	case "gluon.contract.LazyContract.buyer":
		x.Buyer = ""
	case "gluon.contract.LazyContract.seller":
		x.Seller = ""
	case "gluon.contract.LazyContract.denom_base":
		x.DenomBase = ""
	case "gluon.contract.LazyContract.denom_quote":
		x.DenomQuote = ""
	case "gluon.contract.LazyContract.amount_pending_buyer":
		x.AmountPendingBuyer = ""
	case "gluon.contract.LazyContract.amount_pending_seller":
		x.AmountPendingSeller = ""
	case "gluon.contract.LazyContract.amount_escrow_buyer":
		x.AmountEscrowBuyer = ""
	case "gluon.contract.LazyContract.amount_escrow_seller":
		x.AmountEscrowSeller = ""
	case "gluon.contract.LazyContract.expiry":
		x.Expiry = nil
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: gluon.contract.LazyContract"))
		}
		panic(fmt.Errorf("message gluon.contract.LazyContract does not contain field %s", fd.FullName()))
	}
}

// Get retrieves the value for a field.
//
// For unpopulated scalars, it returns the default value, where
// the default value of a bytes scalar is guaranteed to be a copy.
// For unpopulated composite types, it returns an empty, read-only view
// of the value; to obtain a mutable reference, use Mutable.
func (x *fastReflection_LazyContract) Get(descriptor protoreflect.FieldDescriptor) protoreflect.Value {
	switch descriptor.FullName() {
	case "gluon.contract.LazyContract.id":
		value := x.Id
		return protoreflect.ValueOfUint64(value)
	case "gluon.contract.LazyContract.buyer":
		value := x.Buyer
		return protoreflect.ValueOfString(value)
	case "gluon.contract.LazyContract.seller":
		value := x.Seller
		return protoreflect.ValueOfString(value)
	case "gluon.contract.LazyContract.denom_base":
		value := x.DenomBase
		return protoreflect.ValueOfString(value)
	case "gluon.contract.LazyContract.denom_quote":
		value := x.DenomQuote
		return protoreflect.ValueOfString(value)
	case "gluon.contract.LazyContract.amount_pending_buyer":
		value := x.AmountPendingBuyer
		return protoreflect.ValueOfString(value)
	case "gluon.contract.LazyContract.amount_pending_seller":
		value := x.AmountPendingSeller
		return protoreflect.ValueOfString(value)
	case "gluon.contract.LazyContract.amount_escrow_buyer":
		value := x.AmountEscrowBuyer
		return protoreflect.ValueOfString(value)
	case "gluon.contract.LazyContract.amount_escrow_seller":
		value := x.AmountEscrowSeller
		return protoreflect.ValueOfString(value)
	case "gluon.contract.LazyContract.expiry":
		value := x.Expiry
		return protoreflect.ValueOfMessage(value.ProtoReflect())
	default:
		if descriptor.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: gluon.contract.LazyContract"))
		}
		panic(fmt.Errorf("message gluon.contract.LazyContract does not contain field %s", descriptor.FullName()))
	}
}

// Set stores the value for a field.
//
// For a field belonging to a oneof, it implicitly clears any other field
// that may be currently set within the same oneof.
// For extension fields, it implicitly stores the provided ExtensionType.
// When setting a composite type, it is unspecified whether the stored value
// aliases the source's memory in any way. If the composite value is an
// empty, read-only value, then it panics.
//
// Set is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_LazyContract) Set(fd protoreflect.FieldDescriptor, value protoreflect.Value) {
	switch fd.FullName() {
	case "gluon.contract.LazyContract.id":
		x.Id = value.Uint()
	case "gluon.contract.LazyContract.buyer":
		x.Buyer = value.Interface().(string)
	case "gluon.contract.LazyContract.seller":
		x.Seller = value.Interface().(string)
	case "gluon.contract.LazyContract.denom_base":
		x.DenomBase = value.Interface().(string)
	case "gluon.contract.LazyContract.denom_quote":
		x.DenomQuote = value.Interface().(string)
	case "gluon.contract.LazyContract.amount_pending_buyer":
		x.AmountPendingBuyer = value.Interface().(string)
	case "gluon.contract.LazyContract.amount_pending_seller":
		x.AmountPendingSeller = value.Interface().(string)
	case "gluon.contract.LazyContract.amount_escrow_buyer":
		x.AmountEscrowBuyer = value.Interface().(string)
	case "gluon.contract.LazyContract.amount_escrow_seller":
		x.AmountEscrowSeller = value.Interface().(string)
	case "gluon.contract.LazyContract.expiry":
		x.Expiry = value.Message().Interface().(*timestamppb.Timestamp)
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: gluon.contract.LazyContract"))
		}
		panic(fmt.Errorf("message gluon.contract.LazyContract does not contain field %s", fd.FullName()))
	}
}

// Mutable returns a mutable reference to a composite type.
//
// If the field is unpopulated, it may allocate a composite value.
// For a field belonging to a oneof, it implicitly clears any other field
// that may be currently set within the same oneof.
// For extension fields, it implicitly stores the provided ExtensionType
// if not already stored.
// It panics if the field does not contain a composite type.
//
// Mutable is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_LazyContract) Mutable(fd protoreflect.FieldDescriptor) protoreflect.Value {
	switch fd.FullName() {
	case "gluon.contract.LazyContract.expiry":
		if x.Expiry == nil {
			x.Expiry = new(timestamppb.Timestamp)
		}
		return protoreflect.ValueOfMessage(x.Expiry.ProtoReflect())
	case "gluon.contract.LazyContract.id":
		panic(fmt.Errorf("field id of message gluon.contract.LazyContract is not mutable"))
	case "gluon.contract.LazyContract.buyer":
		panic(fmt.Errorf("field buyer of message gluon.contract.LazyContract is not mutable"))
	case "gluon.contract.LazyContract.seller":
		panic(fmt.Errorf("field seller of message gluon.contract.LazyContract is not mutable"))
	case "gluon.contract.LazyContract.denom_base":
		panic(fmt.Errorf("field denom_base of message gluon.contract.LazyContract is not mutable"))
	case "gluon.contract.LazyContract.denom_quote":
		panic(fmt.Errorf("field denom_quote of message gluon.contract.LazyContract is not mutable"))
	case "gluon.contract.LazyContract.amount_pending_buyer":
		panic(fmt.Errorf("field amount_pending_buyer of message gluon.contract.LazyContract is not mutable"))
	case "gluon.contract.LazyContract.amount_pending_seller":
		panic(fmt.Errorf("field amount_pending_seller of message gluon.contract.LazyContract is not mutable"))
	case "gluon.contract.LazyContract.amount_escrow_buyer":
		panic(fmt.Errorf("field amount_escrow_buyer of message gluon.contract.LazyContract is not mutable"))
	case "gluon.contract.LazyContract.amount_escrow_seller":
		panic(fmt.Errorf("field amount_escrow_seller of message gluon.contract.LazyContract is not mutable"))
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: gluon.contract.LazyContract"))
		}
		panic(fmt.Errorf("message gluon.contract.LazyContract does not contain field %s", fd.FullName()))
	}
}

// NewField returns a new value that is assignable to the field
// for the given descriptor. For scalars, this returns the default value.
// For lists, maps, and messages, this returns a new, empty, mutable value.
func (x *fastReflection_LazyContract) NewField(fd protoreflect.FieldDescriptor) protoreflect.Value {
	switch fd.FullName() {
	case "gluon.contract.LazyContract.id":
		return protoreflect.ValueOfUint64(uint64(0))
	case "gluon.contract.LazyContract.buyer":
		return protoreflect.ValueOfString("")
	case "gluon.contract.LazyContract.seller":
		return protoreflect.ValueOfString("")
	case "gluon.contract.LazyContract.denom_base":
		return protoreflect.ValueOfString("")
	case "gluon.contract.LazyContract.denom_quote":
		return protoreflect.ValueOfString("")
	case "gluon.contract.LazyContract.amount_pending_buyer":
		return protoreflect.ValueOfString("")
	case "gluon.contract.LazyContract.amount_pending_seller":
		return protoreflect.ValueOfString("")
	case "gluon.contract.LazyContract.amount_escrow_buyer":
		return protoreflect.ValueOfString("")
	case "gluon.contract.LazyContract.amount_escrow_seller":
		return protoreflect.ValueOfString("")
	case "gluon.contract.LazyContract.expiry":
		m := new(timestamppb.Timestamp)
		return protoreflect.ValueOfMessage(m.ProtoReflect())
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: gluon.contract.LazyContract"))
		}
		panic(fmt.Errorf("message gluon.contract.LazyContract does not contain field %s", fd.FullName()))
	}
}

// WhichOneof reports which field within the oneof is populated,
// returning nil if none are populated.
// It panics if the oneof descriptor does not belong to this message.
func (x *fastReflection_LazyContract) WhichOneof(d protoreflect.OneofDescriptor) protoreflect.FieldDescriptor {
	switch d.FullName() {
	default:
		panic(fmt.Errorf("%s is not a oneof field in gluon.contract.LazyContract", d.FullName()))
	}
	panic("unreachable")
}

// GetUnknown retrieves the entire list of unknown fields.
// The caller may only mutate the contents of the RawFields
// if the mutated bytes are stored back into the message with SetUnknown.
func (x *fastReflection_LazyContract) GetUnknown() protoreflect.RawFields {
	return x.unknownFields
}

// SetUnknown stores an entire list of unknown fields.
// The raw fields must be syntactically valid according to the wire format.
// An implementation may panic if this is not the case.
// Once stored, the caller must not mutate the content of the RawFields.
// An empty RawFields may be passed to clear the fields.
//
// SetUnknown is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_LazyContract) SetUnknown(fields protoreflect.RawFields) {
	x.unknownFields = fields
}

// IsValid reports whether the message is valid.
//
// An invalid message is an empty, read-only value.
//
// An invalid message often corresponds to a nil pointer of the concrete
// message type, but the details are implementation dependent.
// Validity is not part of the protobuf data model, and may not
// be preserved in marshaling or other operations.
func (x *fastReflection_LazyContract) IsValid() bool {
	return x != nil
}

// ProtoMethods returns optional fastReflectionFeature-path implementations of various operations.
// This method may return nil.
//
// The returned methods type is identical to
// "google.golang.org/protobuf/runtime/protoiface".Methods.
// Consult the protoiface package documentation for details.
func (x *fastReflection_LazyContract) ProtoMethods() *protoiface.Methods {
	size := func(input protoiface.SizeInput) protoiface.SizeOutput {
		x := input.Message.Interface().(*LazyContract)
		if x == nil {
			return protoiface.SizeOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Size:              0,
			}
		}
		options := runtime.SizeInputToOptions(input)
		_ = options
		var n int
		var l int
		_ = l
		if x.Id != 0 {
			n += 1 + runtime.Sov(uint64(x.Id))
		}
		l = len(x.Buyer)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		l = len(x.Seller)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		l = len(x.DenomBase)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		l = len(x.DenomQuote)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		l = len(x.AmountPendingBuyer)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		l = len(x.AmountPendingSeller)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		l = len(x.AmountEscrowBuyer)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		l = len(x.AmountEscrowSeller)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		if x.Expiry != nil {
			l = options.Size(x.Expiry)
			n += 1 + l + runtime.Sov(uint64(l))
		}
		if x.unknownFields != nil {
			n += len(x.unknownFields)
		}
		return protoiface.SizeOutput{
			NoUnkeyedLiterals: input.NoUnkeyedLiterals,
			Size:              n,
		}
	}

	marshal := func(input protoiface.MarshalInput) (protoiface.MarshalOutput, error) {
		x := input.Message.Interface().(*LazyContract)
		if x == nil {
			return protoiface.MarshalOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Buf:               input.Buf,
			}, nil
		}
		options := runtime.MarshalInputToOptions(input)
		_ = options
		size := options.Size(x)
		dAtA := make([]byte, size)
		i := len(dAtA)
		_ = i
		var l int
		_ = l
		if x.unknownFields != nil {
			i -= len(x.unknownFields)
			copy(dAtA[i:], x.unknownFields)
		}
		if x.Expiry != nil {
			encoded, err := options.Marshal(x.Expiry)
			if err != nil {
				return protoiface.MarshalOutput{
					NoUnkeyedLiterals: input.NoUnkeyedLiterals,
					Buf:               input.Buf,
				}, err
			}
			i -= len(encoded)
			copy(dAtA[i:], encoded)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(encoded)))
			i--
			dAtA[i] = 0x52
		}
		if len(x.AmountEscrowSeller) > 0 {
			i -= len(x.AmountEscrowSeller)
			copy(dAtA[i:], x.AmountEscrowSeller)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.AmountEscrowSeller)))
			i--
			dAtA[i] = 0x4a
		}
		if len(x.AmountEscrowBuyer) > 0 {
			i -= len(x.AmountEscrowBuyer)
			copy(dAtA[i:], x.AmountEscrowBuyer)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.AmountEscrowBuyer)))
			i--
			dAtA[i] = 0x42
		}
		if len(x.AmountPendingSeller) > 0 {
			i -= len(x.AmountPendingSeller)
			copy(dAtA[i:], x.AmountPendingSeller)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.AmountPendingSeller)))
			i--
			dAtA[i] = 0x3a
		}
		if len(x.AmountPendingBuyer) > 0 {
			i -= len(x.AmountPendingBuyer)
			copy(dAtA[i:], x.AmountPendingBuyer)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.AmountPendingBuyer)))
			i--
			dAtA[i] = 0x32
		}
		if len(x.DenomQuote) > 0 {
			i -= len(x.DenomQuote)
			copy(dAtA[i:], x.DenomQuote)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.DenomQuote)))
			i--
			dAtA[i] = 0x2a
		}
		if len(x.DenomBase) > 0 {
			i -= len(x.DenomBase)
			copy(dAtA[i:], x.DenomBase)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.DenomBase)))
			i--
			dAtA[i] = 0x22
		}
		if len(x.Seller) > 0 {
			i -= len(x.Seller)
			copy(dAtA[i:], x.Seller)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.Seller)))
			i--
			dAtA[i] = 0x1a
		}
		if len(x.Buyer) > 0 {
			i -= len(x.Buyer)
			copy(dAtA[i:], x.Buyer)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.Buyer)))
			i--
			dAtA[i] = 0x12
		}
		if x.Id != 0 {
			i = runtime.EncodeVarint(dAtA, i, uint64(x.Id))
			i--
			dAtA[i] = 0x8
		}
		if input.Buf != nil {
			input.Buf = append(input.Buf, dAtA...)
		} else {
			input.Buf = dAtA
		}
		return protoiface.MarshalOutput{
			NoUnkeyedLiterals: input.NoUnkeyedLiterals,
			Buf:               input.Buf,
		}, nil
	}
	unmarshal := func(input protoiface.UnmarshalInput) (protoiface.UnmarshalOutput, error) {
		x := input.Message.Interface().(*LazyContract)
		if x == nil {
			return protoiface.UnmarshalOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Flags:             input.Flags,
			}, nil
		}
		options := runtime.UnmarshalInputToOptions(input)
		_ = options
		dAtA := input.Buf
		l := len(dAtA)
		iNdEx := 0
		for iNdEx < l {
			preIndex := iNdEx
			var wire uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
				}
				if iNdEx >= l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				wire |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			fieldNum := int32(wire >> 3)
			wireType := int(wire & 0x7)
			if wireType == 4 {
				return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: LazyContract: wiretype end group for non-group")
			}
			if fieldNum <= 0 {
				return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: LazyContract: illegal tag %d (wire type %d)", fieldNum, wire)
			}
			switch fieldNum {
			case 1:
				if wireType != 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
				}
				x.Id = 0
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					x.Id |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
			case 2:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field Buyer", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.Buyer = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			case 3:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field Seller", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.Seller = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			case 4:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field DenomBase", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.DenomBase = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			case 5:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field DenomQuote", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.DenomQuote = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			case 6:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field AmountPendingBuyer", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.AmountPendingBuyer = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			case 7:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field AmountPendingSeller", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.AmountPendingSeller = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			case 8:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field AmountEscrowBuyer", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.AmountEscrowBuyer = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			case 9:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field AmountEscrowSeller", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.AmountEscrowSeller = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			case 10:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field Expiry", wireType)
				}
				var msglen int
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					msglen |= int(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				if msglen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + msglen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				if x.Expiry == nil {
					x.Expiry = &timestamppb.Timestamp{}
				}
				if err := options.Unmarshal(dAtA[iNdEx:postIndex], x.Expiry); err != nil {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, err
				}
				iNdEx = postIndex
			default:
				iNdEx = preIndex
				skippy, err := runtime.Skip(dAtA[iNdEx:])
				if err != nil {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, err
				}
				if (skippy < 0) || (iNdEx+skippy) < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if (iNdEx + skippy) > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				if !options.DiscardUnknown {
					x.unknownFields = append(x.unknownFields, dAtA[iNdEx:iNdEx+skippy]...)
				}
				iNdEx += skippy
			}
		}

		if iNdEx > l {
			return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
		}
		return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, nil
	}
	return &protoiface.Methods{
		NoUnkeyedLiterals: struct{}{},
		Flags:             protoiface.SupportMarshalDeterministic | protoiface.SupportUnmarshalDiscardUnknown,
		Size:              size,
		Marshal:           marshal,
		Unmarshal:         unmarshal,
		Merge:             nil,
		CheckInitialized:  nil,
	}
}

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.0
// 	protoc        (unknown)
// source: gluon/contract/lazy_contract.proto

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LazyContract struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id                  uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Buyer               string                 `protobuf:"bytes,2,opt,name=buyer,proto3" json:"buyer,omitempty"`
	Seller              string                 `protobuf:"bytes,3,opt,name=seller,proto3" json:"seller,omitempty"`
	DenomBase           string                 `protobuf:"bytes,4,opt,name=denom_base,json=denomBase,proto3" json:"denom_base,omitempty"`
	DenomQuote          string                 `protobuf:"bytes,5,opt,name=denom_quote,json=denomQuote,proto3" json:"denom_quote,omitempty"`
	AmountPendingBuyer  string                 `protobuf:"bytes,6,opt,name=amount_pending_buyer,json=amountPendingBuyer,proto3" json:"amount_pending_buyer,omitempty"`
	AmountPendingSeller string                 `protobuf:"bytes,7,opt,name=amount_pending_seller,json=amountPendingSeller,proto3" json:"amount_pending_seller,omitempty"`
	AmountEscrowBuyer   string                 `protobuf:"bytes,8,opt,name=amount_escrow_buyer,json=amountEscrowBuyer,proto3" json:"amount_escrow_buyer,omitempty"`
	AmountEscrowSeller  string                 `protobuf:"bytes,9,opt,name=amount_escrow_seller,json=amountEscrowSeller,proto3" json:"amount_escrow_seller,omitempty"`
	Expiry              *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=expiry,proto3" json:"expiry,omitempty"`
}

func (x *LazyContract) Reset() {
	*x = LazyContract{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gluon_contract_lazy_contract_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LazyContract) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LazyContract) ProtoMessage() {}

// Deprecated: Use LazyContract.ProtoReflect.Descriptor instead.
func (*LazyContract) Descriptor() ([]byte, []int) {
	return file_gluon_contract_lazy_contract_proto_rawDescGZIP(), []int{0}
}

func (x *LazyContract) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *LazyContract) GetBuyer() string {
	if x != nil {
		return x.Buyer
	}
	return ""
}

func (x *LazyContract) GetSeller() string {
	if x != nil {
		return x.Seller
	}
	return ""
}

func (x *LazyContract) GetDenomBase() string {
	if x != nil {
		return x.DenomBase
	}
	return ""
}

func (x *LazyContract) GetDenomQuote() string {
	if x != nil {
		return x.DenomQuote
	}
	return ""
}

func (x *LazyContract) GetAmountPendingBuyer() string {
	if x != nil {
		return x.AmountPendingBuyer
	}
	return ""
}

func (x *LazyContract) GetAmountPendingSeller() string {
	if x != nil {
		return x.AmountPendingSeller
	}
	return ""
}

func (x *LazyContract) GetAmountEscrowBuyer() string {
	if x != nil {
		return x.AmountEscrowBuyer
	}
	return ""
}

func (x *LazyContract) GetAmountEscrowSeller() string {
	if x != nil {
		return x.AmountEscrowSeller
	}
	return ""
}

func (x *LazyContract) GetExpiry() *timestamppb.Timestamp {
	if x != nil {
		return x.Expiry
	}
	return nil
}

var File_gluon_contract_lazy_contract_proto protoreflect.FileDescriptor

var file_gluon_contract_lazy_contract_proto_rawDesc = []byte{
	0x0a, 0x22, 0x67, 0x6c, 0x75, 0x6f, 0x6e, 0x2f, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74,
	0x2f, 0x6c, 0x61, 0x7a, 0x79, 0x5f, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0e, 0x67, 0x6c, 0x75, 0x6f, 0x6e, 0x2e, 0x63, 0x6f, 0x6e, 0x74,
	0x72, 0x61, 0x63, 0x74, 0x1a, 0x11, 0x61, 0x6d, 0x69, 0x6e, 0x6f, 0x2f, 0x61, 0x6d, 0x69, 0x6e,
	0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x14, 0x67, 0x6f, 0x67, 0x6f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2f, 0x67, 0x6f, 0x67, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x19, 0x63,
	0x6f, 0x73, 0x6d, 0x6f, 0x73, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x63, 0x6f, 0x73, 0x6d,
	0x6f, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74,
	0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xda, 0x04, 0x0a, 0x0c, 0x4c, 0x61,
	0x7a, 0x79, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x62, 0x75,
	0x79, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x62, 0x75, 0x79, 0x65, 0x72,
	0x12, 0x16, 0x0a, 0x06, 0x73, 0x65, 0x6c, 0x6c, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x73, 0x65, 0x6c, 0x6c, 0x65, 0x72, 0x12, 0x1d, 0x0a, 0x0a, 0x64, 0x65, 0x6e, 0x6f,
	0x6d, 0x5f, 0x62, 0x61, 0x73, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x64, 0x65,
	0x6e, 0x6f, 0x6d, 0x42, 0x61, 0x73, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x64, 0x65, 0x6e, 0x6f, 0x6d,
	0x5f, 0x71, 0x75, 0x6f, 0x74, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x64, 0x65,
	0x6e, 0x6f, 0x6d, 0x51, 0x75, 0x6f, 0x74, 0x65, 0x12, 0x62, 0x0a, 0x14, 0x61, 0x6d, 0x6f, 0x75,
	0x6e, 0x74, 0x5f, 0x70, 0x65, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x5f, 0x62, 0x75, 0x79, 0x65, 0x72,
	0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x42, 0x30, 0xc8, 0xde, 0x1f, 0x00, 0xda, 0xde, 0x1f, 0x15,
	0x63, 0x6f, 0x73, 0x6d, 0x6f, 0x73, 0x73, 0x64, 0x6b, 0x2e, 0x69, 0x6f, 0x2f, 0x6d, 0x61, 0x74,
	0x68, 0x2e, 0x49, 0x6e, 0x74, 0xd2, 0xb4, 0x2d, 0x0a, 0x63, 0x6f, 0x73, 0x6d, 0x6f, 0x73, 0x2e,
	0x49, 0x6e, 0x74, 0xa8, 0xe7, 0xb0, 0x2a, 0x01, 0x52, 0x12, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74,
	0x50, 0x65, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x42, 0x75, 0x79, 0x65, 0x72, 0x12, 0x64, 0x0a, 0x15,
	0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x5f, 0x70, 0x65, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x5f, 0x73,
	0x65, 0x6c, 0x6c, 0x65, 0x72, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x42, 0x30, 0xc8, 0xde, 0x1f,
	0x00, 0xda, 0xde, 0x1f, 0x15, 0x63, 0x6f, 0x73, 0x6d, 0x6f, 0x73, 0x73, 0x64, 0x6b, 0x2e, 0x69,
	0x6f, 0x2f, 0x6d, 0x61, 0x74, 0x68, 0x2e, 0x49, 0x6e, 0x74, 0xd2, 0xb4, 0x2d, 0x0a, 0x63, 0x6f,
	0x73, 0x6d, 0x6f, 0x73, 0x2e, 0x49, 0x6e, 0x74, 0xa8, 0xe7, 0xb0, 0x2a, 0x01, 0x52, 0x13, 0x61,
	0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x50, 0x65, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x53, 0x65, 0x6c, 0x6c,
	0x65, 0x72, 0x12, 0x60, 0x0a, 0x13, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x5f, 0x65, 0x73, 0x63,
	0x72, 0x6f, 0x77, 0x5f, 0x62, 0x75, 0x79, 0x65, 0x72, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x42,
	0x30, 0xc8, 0xde, 0x1f, 0x00, 0xda, 0xde, 0x1f, 0x15, 0x63, 0x6f, 0x73, 0x6d, 0x6f, 0x73, 0x73,
	0x64, 0x6b, 0x2e, 0x69, 0x6f, 0x2f, 0x6d, 0x61, 0x74, 0x68, 0x2e, 0x49, 0x6e, 0x74, 0xd2, 0xb4,
	0x2d, 0x0a, 0x63, 0x6f, 0x73, 0x6d, 0x6f, 0x73, 0x2e, 0x49, 0x6e, 0x74, 0xa8, 0xe7, 0xb0, 0x2a,
	0x01, 0x52, 0x11, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x45, 0x73, 0x63, 0x72, 0x6f, 0x77, 0x42,
	0x75, 0x79, 0x65, 0x72, 0x12, 0x62, 0x0a, 0x14, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x5f, 0x65,
	0x73, 0x63, 0x72, 0x6f, 0x77, 0x5f, 0x73, 0x65, 0x6c, 0x6c, 0x65, 0x72, 0x18, 0x09, 0x20, 0x01,
	0x28, 0x09, 0x42, 0x30, 0xc8, 0xde, 0x1f, 0x00, 0xda, 0xde, 0x1f, 0x15, 0x63, 0x6f, 0x73, 0x6d,
	0x6f, 0x73, 0x73, 0x64, 0x6b, 0x2e, 0x69, 0x6f, 0x2f, 0x6d, 0x61, 0x74, 0x68, 0x2e, 0x49, 0x6e,
	0x74, 0xd2, 0xb4, 0x2d, 0x0a, 0x63, 0x6f, 0x73, 0x6d, 0x6f, 0x73, 0x2e, 0x49, 0x6e, 0x74, 0xa8,
	0xe7, 0xb0, 0x2a, 0x01, 0x52, 0x12, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x45, 0x73, 0x63, 0x72,
	0x6f, 0x77, 0x53, 0x65, 0x6c, 0x6c, 0x65, 0x72, 0x12, 0x3c, 0x0a, 0x06, 0x65, 0x78, 0x70, 0x69,
	0x72, 0x79, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73,
	0x74, 0x61, 0x6d, 0x70, 0x42, 0x08, 0xc8, 0xde, 0x1f, 0x00, 0x90, 0xdf, 0x1f, 0x01, 0x52, 0x06,
	0x65, 0x78, 0x70, 0x69, 0x72, 0x79, 0x42, 0x9a, 0x01, 0x0a, 0x12, 0x63, 0x6f, 0x6d, 0x2e, 0x67,
	0x6c, 0x75, 0x6f, 0x6e, 0x2e, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x42, 0x11, 0x4c,
	0x61, 0x7a, 0x79, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x50, 0x72, 0x6f, 0x74, 0x6f,
	0x50, 0x01, 0x5a, 0x18, 0x67, 0x6c, 0x75, 0x6f, 0x6e, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x67, 0x6c,
	0x75, 0x6f, 0x6e, 0x2f, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0xa2, 0x02, 0x03, 0x47,
	0x43, 0x58, 0xaa, 0x02, 0x0e, 0x47, 0x6c, 0x75, 0x6f, 0x6e, 0x2e, 0x43, 0x6f, 0x6e, 0x74, 0x72,
	0x61, 0x63, 0x74, 0xca, 0x02, 0x0e, 0x47, 0x6c, 0x75, 0x6f, 0x6e, 0x5c, 0x43, 0x6f, 0x6e, 0x74,
	0x72, 0x61, 0x63, 0x74, 0xe2, 0x02, 0x1a, 0x47, 0x6c, 0x75, 0x6f, 0x6e, 0x5c, 0x43, 0x6f, 0x6e,
	0x74, 0x72, 0x61, 0x63, 0x74, 0x5c, 0x47, 0x50, 0x42, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74,
	0x61, 0xea, 0x02, 0x0f, 0x47, 0x6c, 0x75, 0x6f, 0x6e, 0x3a, 0x3a, 0x43, 0x6f, 0x6e, 0x74, 0x72,
	0x61, 0x63, 0x74, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_gluon_contract_lazy_contract_proto_rawDescOnce sync.Once
	file_gluon_contract_lazy_contract_proto_rawDescData = file_gluon_contract_lazy_contract_proto_rawDesc
)

func file_gluon_contract_lazy_contract_proto_rawDescGZIP() []byte {
	file_gluon_contract_lazy_contract_proto_rawDescOnce.Do(func() {
		file_gluon_contract_lazy_contract_proto_rawDescData = protoimpl.X.CompressGZIP(file_gluon_contract_lazy_contract_proto_rawDescData)
	})
	return file_gluon_contract_lazy_contract_proto_rawDescData
}

var file_gluon_contract_lazy_contract_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_gluon_contract_lazy_contract_proto_goTypes = []interface{}{
	(*LazyContract)(nil),          // 0: gluon.contract.LazyContract
	(*timestamppb.Timestamp)(nil), // 1: google.protobuf.Timestamp
}
var file_gluon_contract_lazy_contract_proto_depIdxs = []int32{
	1, // 0: gluon.contract.LazyContract.expiry:type_name -> google.protobuf.Timestamp
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_gluon_contract_lazy_contract_proto_init() }
func file_gluon_contract_lazy_contract_proto_init() {
	if File_gluon_contract_lazy_contract_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_gluon_contract_lazy_contract_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LazyContract); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_gluon_contract_lazy_contract_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_gluon_contract_lazy_contract_proto_goTypes,
		DependencyIndexes: file_gluon_contract_lazy_contract_proto_depIdxs,
		MessageInfos:      file_gluon_contract_lazy_contract_proto_msgTypes,
	}.Build()
	File_gluon_contract_lazy_contract_proto = out.File
	file_gluon_contract_lazy_contract_proto_rawDesc = nil
	file_gluon_contract_lazy_contract_proto_goTypes = nil
	file_gluon_contract_lazy_contract_proto_depIdxs = nil
}
